/**
 * `stage-report.json` — §13: "Every stage writes a `stage-report.json`: inputs,
 * outputs, duration, warnings, gaps. The CLI prints a digest."
 *
 * `durationMs` lives in `provenance` with the other volatile fields, so a stage
 * report participates in the same idempotency check as everything else.
 */
import { z } from 'zod';
import { Sha256Schema, SiteIdSchema } from './primitives.js';
import { artifactEnvelope } from './artifact.js';
import { GapSchema, StageNameSchema } from './gap.js';
import { InferMetricsBlockSchema } from './grade-contract.js';

/** A file a stage read or wrote, with its hash, so the DAG is checkable. */
export const FileRefSchema = z.strictObject({
  /** Relative to the capture or env root. */
  path: z.string().min(1),
  sha256: Sha256Schema,
  bytes: z.int().nonnegative(),
});

export const StageStatusSchema = z.enum([
  'ok',
  /** Completed, but wrote gaps. The normal outcome for a real site. */
  'ok-with-gaps',
  /** A gate failed. §13: "Never `--force` past a failing gate." */
  'failed',
]);

export const StageWarningSchema = z.strictObject({
  code: z.string().min(1),
  message: z.string().min(1),
  /** Where it applies, when it applies somewhere specific. */
  path: z.string().optional(),
});

/**
 * What infer adds to its report, and no other stage may.
 *
 * Decision 0015 §7.1: the **first** infer stage report — written before any
 * grade has ever run — carries the scored-field contract, so what is being
 * measured can be read separately from how it did. `authUnknown` is 0014's
 * ruling in the same place: `unknown` resolves to required, and a large set is a
 * shallow anonymous crawl the operator wants to see rather than have a
 * permissive default hide.
 *
 * Per-stage rather than a field on every report: an optional `metrics` on
 * `StageReportSchema` would put an infer-only concern on capture, codegen and
 * verify, where "absent" would mean nothing at all.
 */
export const InferStageDetailSchema = z.strictObject({
  stage: z.literal('infer'),
  metrics: InferMetricsBlockSchema,
  /** §8: endpoints codegen will gate because nothing was ever observed. */
  authUnknownEndpointIds: z.array(z.string().min(1)),
});

export const StageReportSchema = z
  .strictObject({
    ...artifactEnvelope('stage-report'),
    stage: StageNameSchema,
    siteId: SiteIdSchema,
    status: StageStatusSchema,
    inputs: z.array(FileRefSchema),
    outputs: z.array(FileRefSchema),
    warnings: z.array(StageWarningSchema),
    /** Full gap records. `GAPS.md` is generated by aggregating these across stages. */
    gaps: z.array(GapSchema),
    /** Required for `infer`, forbidden elsewhere — see the refinement below. */
    detail: InferStageDetailSchema.optional(),
  })
  .superRefine((report, ctx) => {
    // A biconditional, not a permission. Optional-and-encouraged is how a
    // required report becomes one nobody writes: the first infer run that
    // forgot it would parse, and §7.1's whole point is that the contract is
    // visible before the first score.
    if (report.stage === 'infer' && report.detail === undefined) {
      ctx.addIssue({
        code: 'custom',
        path: ['detail'],
        message:
          'an infer stage report carries the scored-field contract (0015 §7.1) — what is measured is reported before how it did',
      });
    }
    if (report.stage !== 'infer' && report.detail !== undefined) {
      ctx.addIssue({
        code: 'custom',
        path: ['detail'],
        message: `only infer carries a stage detail; this report is for ${report.stage}`,
      });
    }
  });

export type FileRef = z.infer<typeof FileRefSchema>;
export type StageStatus = z.infer<typeof StageStatusSchema>;
export type StageWarning = z.infer<typeof StageWarningSchema>;
export type InferStageDetail = z.infer<typeof InferStageDetailSchema>;
export type StageReport = z.infer<typeof StageReportSchema>;
