/**
 * `stage-report.json` — §13: "Every stage writes a `stage-report.json`: inputs,
 * outputs, duration, warnings, gaps. The CLI prints a digest."
 *
 * `durationMs` lives in `provenance` with the other volatile fields, so a stage
 * report participates in the same idempotency check as everything else.
 */
import { z } from 'zod';
import { Sha256Schema, SiteIdSchema } from './primitives.js';
import { artifactEnvelope } from './artifact.js';
import { GapSchema, StageNameSchema } from './gap.js';

/** A file a stage read or wrote, with its hash, so the DAG is checkable. */
export const FileRefSchema = z.strictObject({
  /** Relative to the capture or env root. */
  path: z.string().min(1),
  sha256: Sha256Schema,
  bytes: z.int().nonnegative(),
});

export const StageStatusSchema = z.enum([
  'ok',
  /** Completed, but wrote gaps. The normal outcome for a real site. */
  'ok-with-gaps',
  /** A gate failed. §13: "Never `--force` past a failing gate." */
  'failed',
]);

export const StageWarningSchema = z.strictObject({
  code: z.string().min(1),
  message: z.string().min(1),
  /** Where it applies, when it applies somewhere specific. */
  path: z.string().optional(),
});

export const StageReportSchema = z.strictObject({
  ...artifactEnvelope('stage-report'),
  stage: StageNameSchema,
  siteId: SiteIdSchema,
  status: StageStatusSchema,
  inputs: z.array(FileRefSchema),
  outputs: z.array(FileRefSchema),
  warnings: z.array(StageWarningSchema),
  /** Full gap records. `GAPS.md` is generated by aggregating these across stages. */
  gaps: z.array(GapSchema),
});

export type FileRef = z.infer<typeof FileRefSchema>;
export type StageStatus = z.infer<typeof StageStatusSchema>;
export type StageWarning = z.infer<typeof StageWarningSchema>;
export type StageReport = z.infer<typeof StageReportSchema>;
