/**
 * `GAPS.md` — the aggregation §1 requires and nobody ever wrote.
 *
 * §1 lists it as a required output of every run: "a `GAPS.md` listing
 * everything that could not be cloned, with each gap explicitly stubbed rather
 * than silently faked". `GapSchema` exists, its docstring says the point of the
 * category enum "is that `GAPS.md` can be aggregated and counted",
 * `StageReportSchema.gaps` says "`GAPS.md` is generated by aggregating these
 * across stages", and `capture-site.mjs` fills a `gaps` array and ships 43 of
 * them in a real run's stage report.
 *
 * The file said `_No runs recorded yet._` the entire time.
 *
 * **This is §13's third vacuity cause at the top level** — the producer runs,
 * the consumer was never written, the artifact is full and the output is empty
 * — on a deliverable the mission statement names. It is the discriminator that
 * table gives you (is the input empty, or is the input full and the output
 * still empty?) applied to the product rather than to a metric, and no gate
 * noticed for the life of the project because no gate was looking at the file.
 *
 * ### Two sides, both parameters
 *
 * `assessGapAggregation` takes the runs and the markdown and nothing else.
 * §13: a gate only the real run can call is a gate nobody can prove fires, and
 * a check living inside `capture-site.mjs` after the append would be exactly
 * that — it could only ever run on input that had just been written correctly.
 * Here the two sides are handed in, so a test can hand it a run whose gaps
 * never reached the file, which is the state the repository was in.
 *
 * ### The set difference runs both ways
 *
 * §13's two-views rule, and the reason is the same one: an aggregate hides a
 * partial loss. A row in the file with no gap behind it is as much a defect as
 * a gap with no row — the first means the file is describing a run that no
 * longer exists (or a hand edit), the second means the append dropped
 * something. Counting rows against `gaps.length` would catch neither if one of
 * each happened in the same run.
 */

import type { Gap, StageName } from '@siteforge/schema';

/** Where the generated block starts and ends. Everything outside is prose. */
export const GAPS_BEGIN = '<!-- siteforge:gaps:begin -->';
export const GAPS_END = '<!-- siteforge:gaps:end -->';

/** The text the file ships with, and which must not survive a run with gaps. */
export const GAPS_PLACEHOLDER = '_No runs recorded yet._';

/**
 * One stage report's worth of gaps, keyed by the run that produced them.
 *
 * `runId` rather than a timestamp, because two runs a second apart are two
 * runs and the file has to be able to say so. It comes from
 * `provenance.runId`, which every artifact envelope already carries.
 */
export interface GapRun {
  readonly siteId: string;
  readonly stage: StageName;
  readonly runId: string;
  readonly capturedAt: string;
  readonly gaps: readonly Gap[];
  /**
   * `manifest.counts.gaps`, where the run has a manifest.
   *
   * Handed in so the two artifacts that already hold this number can be
   * reconciled rather than merely both existing. The contract file's own rule
   * is that a derived value must not be duplicated across artifacts — one side
   * computes it, the other references it — and nothing has ever checked that
   * these two agree. Optional because `infer` and later stages write a stage
   * report and no manifest.
   */
  readonly manifestGapCount?: number;
}

export type GapAggregationProblem =
  /** The generated block's markers are absent, out of order, or duplicated. */
  | 'markers-unusable'
  /** A run produced gaps and the file has no section for it. The ruling's gate. */
  | 'run-unaggregated'
  /** The run has a section and this gap is not in it. */
  | 'gap-unaggregated'
  /** A row names a gap no supplied run carries. The other direction. */
  | 'row-without-gap'
  /** Runs exist and the shipped placeholder is still in the block. */
  | 'placeholder-retained'
  /** `manifest.counts.gaps` disagrees with the records in the stage report. */
  | 'manifest-count-disagrees'
  /**
   * Nothing was supplied to aggregate.
   *
   * Reported rather than passing silently: §13's precondition rule, and this
   * check is the exact shape it warns about — "no runs, so nothing is missing"
   * and "every run aggregated" both render as an empty finding list. The
   * caller decides whether zero runs is legal for it; the assessment refuses
   * to let that decision be made by omission.
   */
  | 'no-runs-supplied';

export interface GapAggregationFinding {
  readonly problem: GapAggregationProblem;
  readonly detail: string;
  readonly runId?: string;
  readonly gapId?: string;
}

/**
 * The block, split into the per-run sections it is made of.
 *
 * Sections matter to the check, not just to the reader. `GAPS.md` aggregates
 * **across runs** and is tracked by git, while the stage reports it is built
 * from live under a gitignored `capture/` — so a clone of this repository has
 * every row and not one of the runs behind them. §13's two-views rule, and it
 * bit this check on its first `verify:clean`: comparing the file's rows
 * against whatever runs happen to be on *this* machine reported all 50 as
 * orphans, and a transient capture tree another gate's control created was
 * enough to make it non-empty and fire.
 *
 * So a row is only ever checked against a run that was supplied. A section
 * for a run this machine does not have is a past run, which is the file
 * doing its job.
 */
function sectionsOf(body: string): Map<string, string> {
  const out = new Map<string, string>();
  // Split on the heading marker rather than on `###`, so prose in a summary
  // that happens to start with hashes cannot open a phantom section.
  const parts = body.split(/^### /m);
  for (const part of parts.slice(1)) {
    const heading = `### ${part.slice(0, part.indexOf('\n') === -1 ? part.length : part.indexOf('\n'))}`.trimEnd();
    out.set(heading, part);
  }
  return out;
}

/** The one place the generated block is recognised, for both writing and checking. */
function generatedBlock(markdown: string): { body: string } | null {
  const begins = markdown.split(GAPS_BEGIN).length - 1;
  const ends = markdown.split(GAPS_END).length - 1;
  if (begins !== 1 || ends !== 1) return null;
  const from = markdown.indexOf(GAPS_BEGIN) + GAPS_BEGIN.length;
  const to = markdown.indexOf(GAPS_END);
  if (to < from) return null;
  return { body: markdown.slice(from, to) };
}

/** A run's heading. Also the key the check looks for, so the two cannot drift. */
export const runHeading = (run: GapRun): string =>
  `### ${run.siteId} · ${run.stage} · ${run.runId}`;

const cell = (value: string): string => value.replace(/\|/g, '\\|').replace(/\n/g, ' ');

/** What the gap is about, from whichever subject fields are present. */
const subjectOf = (gap: Gap): string => {
  const parts = Object.entries(gap.subject)
    .filter(([, v]) => v !== undefined)
    .map(([k, v]) => `${k}=${String(v)}`);
  // empty: `GapSchema.subject` refines that at least one field is present, so
  // an empty list here is a gap that did not parse — say so rather than render
  // a blank cell that reads like a subject nobody filled in.
  return parts.length === 0 ? '**no subject**' : parts.join(' ');
};

/**
 * Render the generated block for a set of runs.
 *
 * Deterministic: runs sorted by (siteId, stage, runId), gaps by gapId. Two
 * aggregations of the same reports produce the same bytes, which is what lets
 * the check compare rather than re-derive.
 */
export function renderGapsBlock(runs: readonly GapRun[]): string {
  if (runs.length === 0) return `\n${GAPS_PLACEHOLDER}\n`;
  const ordered = [...runs].sort((a, b) =>
    a.siteId.localeCompare(b.siteId) || a.stage.localeCompare(b.stage) || a.runId.localeCompare(b.runId),
  );
  const out: string[] = [''];
  for (const run of ordered) {
    out.push(runHeading(run));
    out.push('');
    out.push(`*${run.capturedAt} — ${run.gaps.length} gap(s).*`);
    out.push('');
    if (run.gaps.length === 0) {
      // The §1 wording this exists to honour: an empty section means the stage
      // ran clean, not that the stage was skipped. So say which.
      out.push('The stage ran clean. No gap was recorded.');
      out.push('');
      continue;
    }
    out.push('| severity | category | subject | stub | summary |');
    out.push('|---|---|---|---|---|');
    for (const gap of [...run.gaps].sort((a, b) => a.gapId.localeCompare(b.gapId))) {
      out.push(
        `| ${gap.severity} | ${cell(gap.category)} | ${cell(subjectOf(gap))} ` +
        `| ${cell(gap.stub.kind)} | <a id="${gap.gapId}"></a>${cell(gap.summary)} |`,
      );
    }
    out.push('');
  }
  return `${out.join('\n')}\n`;
}

/** Splice a freshly rendered block into the file, leaving the prose alone. */
export function writeGapsBlock(markdown: string, runs: readonly GapRun[]): string {
  const block = generatedBlock(markdown);
  if (block === null) {
    throw new Error(
      `GAPS.md has no usable ${GAPS_BEGIN} … ${GAPS_END} block. Refusing to guess where the ` +
      'generated section goes: rewriting the whole file would discard the prose above it, and ' +
      'an operation that restores more than it changed is a different operation (§13).',
    );
  }
  const from = markdown.indexOf(GAPS_BEGIN) + GAPS_BEGIN.length;
  const to = markdown.indexOf(GAPS_END);
  return markdown.slice(0, from) + renderGapsBlock(runs) + markdown.slice(to);
}

/**
 * Does the file describe these runs?
 *
 * Anchors on the gap id rather than on the rendered row, deliberately. A row's
 * text is prose that will be reworded; the id is the identity, and matching on
 * text would make every wording change look like a dropped gap — which is how
 * a check gets disabled for being noisy. The id is emitted into the row as an
 * anchor so it is present in the file for exactly this comparison.
 */
export function assessGapAggregation(input: {
  readonly runs: readonly GapRun[];
  readonly markdown: string;
}): GapAggregationFinding[] {
  const findings: GapAggregationFinding[] = [];
  const block = generatedBlock(input.markdown);
  if (block === null) {
    findings.push({
      problem: 'markers-unusable',
      detail:
        `expected exactly one ${GAPS_BEGIN} and one ${GAPS_END}, in that order. The generated ` +
        'block is rewritten in place, so a lost or duplicated marker silently sends the next ' +
        'aggregation somewhere else — or nowhere.',
    });
    // Every remaining check reads the block, so continuing would report the
    // whole file missing rather than the one defect that caused it.
    return findings;
  }

  if (input.runs.length === 0) {
    findings.push({
      problem: 'no-runs-supplied',
      detail:
        'nothing was handed to the aggregator. An empty finding list would otherwise mean ' +
        'both "no runs exist" and "every run is aggregated", which is the measurement whose ' +
        'failure mode produces its own expected output (§13).',
    });
    return findings;
  }

  const body = block.body;
  if (body.includes(GAPS_PLACEHOLDER)) {
    findings.push({
      problem: 'placeholder-retained',
      detail: `${input.runs.length} run(s) supplied and the shipped placeholder is still in the block`,
    });
  }

  const sections = sectionsOf(body);
  for (const run of input.runs) {
    if (run.manifestGapCount !== undefined && run.manifestGapCount !== run.gaps.length) {
      findings.push({
        problem: 'manifest-count-disagrees',
        runId: run.runId,
        detail:
          `manifest.counts.gaps is ${run.manifestGapCount} and the stage report carries ` +
          `${run.gaps.length} record(s). The records are canonical; the count references them.`,
      });
    }
    const section = sections.get(runHeading(run));
    if (section === undefined) {
      findings.push({
        problem: 'run-unaggregated',
        runId: run.runId,
        detail:
          `${run.siteId} · ${run.stage} produced ${run.gaps.length} gap(s) and GAPS.md has no ` +
          'section for the run. §1 requires the listing; a gap recorded only in a stage report ' +
          'is not the deliverable.',
      });
      continue;
    }
    const mine = new Set(run.gaps.map((g) => g.gapId));
    for (const gap of run.gaps) {
      if (!section.includes(gap.gapId)) {
        findings.push({
          problem: 'gap-unaggregated',
          runId: run.runId,
          gapId: gap.gapId,
          detail: `${gap.category} (${gap.severity}) is in the stage report and not in the file`,
        });
      }
    }

    /**
     * The other direction, **scoped to this run's own section**.
     *
     * A row nothing produced means the file asserts a gap the run behind it
     * does not carry — a dropped gap or a hand edit. Scoped, because the
     * unscoped form compares against runs that are simply not on this
     * machine and reports the whole file as orphaned.
     */
    for (const rowId of section.match(/gap_[0-9a-f]{12}/g) ?? []) {
      if (!mine.has(rowId)) {
        findings.push({
          problem: 'row-without-gap',
          runId: run.runId,
          gapId: rowId,
          detail:
            `GAPS.md lists this gap under ${run.siteId} · ${run.stage} · ${run.runId} and that ` +
            'run’s stage report does not carry it. Either a gap was dropped or the file was ' +
            'edited by hand.',
        });
      }
    }
  }
  return findings;
}
