#!/usr/bin/env node
/**
 * Aggregate every capture run's gaps into `GAPS.md`, and check that they got there.
 *
 *   node scripts/aggregate-gaps.mjs           # rewrite the generated block
 *   node scripts/aggregate-gaps.mjs --check   # fail if the file is behind
 *
 * §1 names `GAPS.md` as a required output of every run. `GapSchema` was
 * written, `capture-site.mjs` fills a `gaps` array, `StageReportSchema.gaps`
 * documents that "GAPS.md is generated by aggregating these across stages" —
 * and the consumer was never written, so a real Vikunja crawl put 43 gaps in
 * its stage report while the file said `_No runs recorded yet._`.
 *
 * **Filesystem view, deliberately.** `capture/` is gitignored (§3.4), so every
 * stage report this reads is invisible to git by construction. A walk driven
 * off `git ls-files` would find nothing and report clean forever — §13's
 * two-views rule, which has produced four separate defects in this repository
 * already.
 *
 * The judgement is not here. `assessGapAggregation` takes the runs and the
 * markdown as parameters so a test can drive it to a failing verdict on input
 * this script cannot produce; this file is the wiring that finds the two sides.
 */
import { existsSync, readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { assessGapAggregation, writeGapsBlock } from '../packages/shared/dist/index.js';

const REPO = join(dirname(fileURLToPath(import.meta.url)), '..');
const CAPTURE = join(REPO, 'capture');
const GAPS_MD = join(REPO, 'GAPS.md');
const check = process.argv.includes('--check');

const readJson = (path) => JSON.parse(readFileSync(path, 'utf8'));

/**
 * Every stage report under `capture/`.
 *
 * One level deep by site id, and `<siteId>-diagnostics` directories are
 * skipped by having no stage report rather than by name — a name test would
 * be the substring-for-token family (§13) and would silently start excluding
 * a site someone named `foo-diagnostics`.
 */
function collectRuns() {
  if (!existsSync(CAPTURE)) return [];
  const runs = [];
  for (const name of readdirSync(CAPTURE)) {
    const dir = join(CAPTURE, name);
    if (!statSync(dir).isDirectory()) continue;
    const reportPath = join(dir, 'stage-report.json');
    if (!existsSync(reportPath)) continue;
    const report = readJson(reportPath);
    const manifestPath = join(dir, 'manifest.json');
    const manifest = existsSync(manifestPath) ? readJson(manifestPath) : null;
    runs.push({
      siteId: report.siteId,
      stage: report.stage,
      runId: report.provenance.runId,
      // `ProvenanceSchema` requires it, so a missing value means this is not a
      // stage report and the run should not be aggregated as though it were.
      capturedAt: report.provenance.recordedAt,
      gaps: report.gaps,
      ...(manifest?.counts?.gaps === undefined ? {} : { manifestGapCount: manifest.counts.gaps }),
    });
  }
  return runs;
}

const runs = collectRuns();
const before = readFileSync(GAPS_MD, 'utf8');

if (!check) {
  const after = writeGapsBlock(before, runs);
  if (after !== before) writeFileSync(GAPS_MD, after);
  const total = runs.reduce((n, r) => n + r.gaps.length, 0);
  console.log(
    `GAPS.md ${after === before ? 'already current' : 'updated'} — ` +
    `${runs.length} run(s), ${total} gap(s).`,
  );
}

const findings = assessGapAggregation({ runs, markdown: readFileSync(GAPS_MD, 'utf8') });

/**
 * Zero runs is reported, never inferred as clean.
 *
 * A machine with no `capture/` tree is a legitimate state — a fresh clone is
 * one — and a machine whose crawl wrote a report the aggregator failed to read
 * is not. Both hand `assessGapAggregation` an empty list, so the two are
 * separated here, where the difference is observable: does the directory
 * exist? §13's precondition rule, on the one input this script can get wrong
 * without anything throwing.
 */
const onlyNoRuns = findings.length === 1 && findings[0].problem === 'no-runs-supplied';
if (onlyNoRuns) {
  const why = existsSync(CAPTURE)
    ? `capture/ exists and holds no stage report — ${readdirSync(CAPTURE).length} entr(y|ies), none with one`
    : 'no capture/ tree on this machine';
  console.log(`  gap aggregation: nothing to aggregate — ${why}.`);
  process.exit(0);
}

if (findings.length > 0) {
  console.log(`\n✗ GAPS.md does not describe ${findings.length} thing(s) it must (§1):`);
  for (const f of findings) {
    const where = [f.runId, f.gapId].filter(Boolean).join(' ');
    console.log(`    ${f.problem}${where ? ` (${where})` : ''} — ${f.detail}`);
  }
  console.log('\n  Run `node scripts/aggregate-gaps.mjs` to rebuild the generated block.');
  process.exit(1);
}
console.log(`  gap aggregation: GAPS.md carries every gap from ${runs.length} run(s). ✓`);
